INSERT INTO ROLE (ID, NAME) VALUES (1, 'ROLE_ADMIN');
INSERT INTO ROLE (ID, NAME) VALUES (2, 'ROLE_VENDOR');
INSERT INTO ROLE (ID, NAME) VALUES (3, 'ROLE_CLIENT');

INSERT INTO USERS (ID, USERNAME, PASSWORD, EMAIL) VALUES (1, 'admin', 'admin', 'admin@proyectofs.com');
INSERT INTO USERS (ID, USERNAME, PASSWORD, EMAIL) VALUES (2, 'vendor', 'vendor', 'vendor@proyectofs.com');
INSERT INTO USERS (ID, USERNAME, PASSWORD, EMAIL) VALUES (3, 'client', 'client', 'client@proyectofs.com');

INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (2, 2);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (3, 3);

INSERT INTO PRODUCT (ID, NAME, DESCRIPTION, PRICE) VALUES (1, 'Producto A', 'Descripcion A', 9.99);
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION, PRICE) VALUES (2, 'Producto B', 'Descripcion B', 19.99);
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION, PRICE) VALUES (3, 'Producto C', 'Descripcion C', 29.99);
